server:
  port: 8080 #端口号
  servlet:
    encoding: #编码
      force: true
      charset: UTF-8
      enabled: true
  tomcat:
    uri-encoding: UTF-8

spring:
  profiles:
    active: jdbc  # 外围jdbc配置文件,对应application-jdbc.yml
  application:
    name: blog_server

# Mybatis-plus
Mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl #输出详细信息到控制台
  mapper-locations: classpath*:/mapper/*.xml  #配置MyBatis的xml映射文件路径


#自定义配置
uploadImagesDir: D:\Springboot\img\images\
uploadAvatarsDir: D:\Springboot\img\avatars\